name: Publish Gem
on:
  release:
    types: [published]
jobs:
  publish:
    uses: flytedesk/.github/.github/workflows/reusable-ruby-gem-publish.yml@main
    with:
      gem_name: pack_api
    secrets: inherit
